### PR TITLE
Added GPLv2 License as of README.md

### PR DESCRIPTION
**Pull request by sspreitzer**

### CODE REVIEW

**Comment by pritambaral** [comment]
I don't think a separate file to cite the license is needed, since it is already mentioned in the README, but I don't mind it.

However, we should stick to upstream's (Realtek's) conventions, who stuck to their upstream's (hostap's) convention of naming the file `COPYING`, and who dual licensed their (pre-2012) releases under BSD and GPLv2. Also, I do not think we need to cite the full license text.

Have a look upstream: https://w1.fi/cgit/hostap/tree/COPYING

**Comment by sspreitzer** [comment]
File renamed to COPYING.
Technically wise I agree with your opinion. Legal wise I would like to have a copy of the license agreement with the source code bundle. This to satisfy the lawyers instead of the techies. Waste of bits but not rights.

**Comment by pritambaral** [comment]
Of course. I don't mind the few extra bytes.

If we are going the full legal way, I'd want the legal text to be unmodified from the original. Having checked Realtek's code dump against hostap's, I can say their text is identical to [hostap's from that time](https://w1.fi/cgit/hostap/plain/COPYING?id=hostap_0_7_2). If you could you copy over content from there, I can pull it in.

**Comment by sspreitzer** [comment]
This project seems dead and closed source. Closing PR.

**Pull request closed without merging**
